# Generated by Django 4.2 on 2024-08-15 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('session_key', models.CharField(blank=True, max_length=50, null=True)),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('adaptations', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='goods.adaptations', verbose_name='Приспособления для вязания')),
                ('products', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='goods.products', verbose_name='Аксессуары')),
            ],
            options={
                'verbose_name': 'Корзину',
                'verbose_name_plural': 'Корзина',
                'db_table': 'cart',
            },
        ),
    ]
