# Generated by Django 4.2 on 2024-07-31 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adaptations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='goods_images', verbose_name='Изображение')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Цена')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('compound', models.CharField(blank=True, max_length=250, null=True, verbose_name='Состав')),
                ('equipment', models.TextField(blank=True, null=True, verbose_name='Комплектация')),
                ('length', models.CharField(blank=True, max_length=300, null=True, verbose_name='Длина лески(для спиц)')),
                ('length1', models.CharField(blank=True, max_length=300, null=True, verbose_name='Длина спицы\\крючка')),
                ('size', models.CharField(blank=True, max_length=300, null=True, verbose_name='Диаметр спицы\\крючка')),
                ('manufacturer', models.CharField(blank=True, max_length=250, null=True, verbose_name='Производитель')),
                ('country', models.CharField(blank=True, max_length=250, null=True, verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Приспособление для вязания',
                'verbose_name_plural': 'Приспособление для вязания',
                'db_table': 'adaptations',
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категорию товара',
                'verbose_name_plural': 'Категории товара',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='YarnCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категорию пряжи',
                'verbose_name_plural': 'Категории пряжи',
                'db_table': 'yarncategory',
            },
        ),
        migrations.CreateModel(
            name='YarnSubCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Подкатегория пряжи')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcategories', to='goods.yarncategories', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Подкатегорию пряжи',
                'verbose_name_plural': 'Подкатегории пряжи',
                'db_table': 'yarnsubcategory',
            },
        ),
        migrations.CreateModel(
            name='Yarn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='goods_images', verbose_name='Изображение')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Цена')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('color', models.CharField(blank=True, max_length=250, verbose_name='Цвет')),
                ('length', models.CharField(blank=True, max_length=250, null=True, verbose_name='Длина нити в мотке(метров)')),
                ('weight', models.IntegerField(blank=True, null=True, verbose_name='Вес мотка')),
                ('compound', models.CharField(blank=True, max_length=300, verbose_name='Состав')),
                ('country', models.CharField(blank=True, max_length=255, verbose_name='Страна')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='goods.yarnsubcategories', verbose_name='Подкатегория')),
            ],
            options={
                'verbose_name': 'Пряжа',
                'verbose_name_plural': 'Пряжа',
                'db_table': 'yarn',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='goods_images', verbose_name='Изображение')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Цена')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='goods.categories', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'db_table': 'product',
            },
        ),
    ]
