# Generated by Django 4.2 on 2024-08-25 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yarn',
            options={'ordering': ('id',), 'verbose_name': 'Пряжа', 'verbose_name_plural': 'Пряжа'},
        ),
        migrations.AlterModelOptions(
            name='yarncategories',
            options={'ordering': ('id',), 'verbose_name': 'Категорию пряжи', 'verbose_name_plural': 'Категории пряжи'},
        ),
        migrations.AlterModelOptions(
            name='yarnsubcategories',
            options={'ordering': ('id',), 'verbose_name': 'Подкатегорию пряжи', 'verbose_name_plural': 'Подкатегории пряжи'},
        ),
        migrations.AlterField(
            model_name='adaptations',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Цена'),
        ),
    ]
